#!/bin/bash                                                                                                                     

                                                                                                                                

git add .                                                                                                                       

                                                                                                                                

git commit -m "update on project"                                                                                               

                                                                                                                                

git push                                                                                                                        

                                                                                                                                

         
